// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace OvertakeAIML.Model
{
    public class ModelInput
    {
        [ColumnName("InitialSeperation"), LoadColumn(0)]
        public float InitialSeperation { get; set; }


        [ColumnName("OvertakingSpeed"), LoadColumn(1)]
        public float OvertakingSpeed { get; set; }


        [ColumnName("OncomingSpeed"), LoadColumn(2)]
        public float OncomingSpeed { get; set; }


        [ColumnName("Success"), LoadColumn(3)]
        public string Success { get; set; }


    }
}
